### ISSUE TITLE
Can't connect to another service without modifying Grind init

### ISSUE THREAD

**Issue by RidleyLarsen** [russross/codegrinder#1]
The `grind init` command will only request a user's cookie from dorking.cs.dixie.edu - It doesn't check for a config file before relying on `defaultHost`.

Plus, after running `grind init`, your config file will be overwritten with `host: defaultHost` anyway. Perhaps it could be a two-step process? Enter your CodeGrinder server hostname --> Enter your cookie.

**Comment by russross** [comment]
That's an issue I still need to work out. For now, just ignore it (go to
the correct URL and ignore the one it suggests) and change the config file
to the host you are using. grind should use the host in your config file
once it has been set.
- Russ

**Comment by RidleyLarsen** [comment]
Here's a potential solution: codechangers/codegrinder@3b7493212a64b347e1da81b6e533966ddef9e3f0

**Comment by russross** [comment]
I changed this a while back. Now the host name is required when you run "grind init". There are no more hard-coded assumptions about hostnames.
