### ISSUE TITLE
Change Canvas Assignment Path

### ISSUE THREAD

**Issue by Coconuttys** [russross/codegrinder#8]
Hello! Is there any way to change the directory path for the canvas folder that is automatically generated when you download new assignments? If so would you mind laying out the steps for me?

**Comment by russross** [comment]
It always creates a 2-level directory structure (course/problem-set) or a 3-level structure for problem sets with multiple problems (course/problem-set/problem) and the root of this structure defaults to your home directory. You can specify an alternate root directory when running `grind get`, e.g.:

    grind get 1234 ~/Documents/homework-root/

but there is currently no way to change the default. You must specify the alternate root each time you run `grind get`. Outside of `grind get` the tool only cares about the problem-set directory and below, so you can freely move directories around if you want to.
